"""initial schema

Revision ID: f9012ba1bc5d
Revises: 
Create Date: 2026-09-22 10:57:21.242601+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models  # noqa: F401 - custom GUID / DateTimeTZ types

revision = 'f9012ba1bc5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_outbox',
    sa.Column('audience', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('published_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), nullable=False),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_unpublished', 'event_outbox', ['published_at'], unique=False)
    op.create_table('llm_providers',
    sa.Column('type', sa.Enum('anthropic', 'openai', 'azure_openai', 'google_gemini', 'openrouter', 'openai_compatible', 'mock', name='provider_type', native_enum=False, length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('api_key_enc', sa.LargeBinary(), nullable=True),
    sa.Column('base_url', sa.String(length=1000), nullable=True),
    sa.Column('default_model', sa.String(length=200), nullable=True),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=False),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name', name='uq_provider_display_name')
    )
    op.create_table('profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('theme_id', app.models.GUID(length=36), nullable=True),
    sa.Column('provider_id', app.models.GUID(length=36), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('shared_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='profile_status', native_enum=False, length=32), nullable=False),
    sa.Column('active_prompt_version_id', app.models.GUID(length=36), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['active_prompt_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prompt_versions',
    sa.Column('profile_id', app.models.GUID(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('change_note', sa.String(length=500), nullable=True),
    sa.Column('created_by', app.models.GUID(length=36), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'version_no', name='uq_prompt_version')
    )
    op.create_index(op.f('ix_prompt_versions_profile_id'), 'prompt_versions', ['profile_id'], unique=False)
    op.create_table('system_metrics',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('value_int', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_key'), 'system_metrics', ['key'], unique=True)
    op.create_table('themes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='theme_status', native_enum=False, length=32), nullable=False),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('maker', 'manager', 'reviewer', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('last_login_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('worker_heartbeats',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('queues', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('concurrency', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('started_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('last_heartbeat_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_log',
    sa.Column('actor_id', app.models.GUID(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_table('daily_maker_stats',
    sa.Column('maker_id', app.models.GUID(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('submitted', sa.Integer(), nullable=False),
    sa.Column('ready', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Integer(), nullable=False),
    sa.Column('avg_ready_ms', sa.Integer(), nullable=True),
    sa.Column('avg_llm_attempts', sa.Float(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['maker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maker_id', 'date', name='uq_daily_maker_stat')
    )
    op.create_index(op.f('ix_daily_maker_stats_maker_id'), 'daily_maker_stats', ['maker_id'], unique=False)
    op.create_table('interview_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', app.models.GUID(length=36), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('maker_id', app.models.GUID(length=36), nullable=False),
    sa.Column('profile_id', app.models.GUID(length=36), nullable=True),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=False),
    sa.Column('submitted_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('jd_hash', sa.String(length=64), nullable=False),
    sa.Column('duplicate_of', app.models.GUID(length=36), nullable=True),
    sa.Column('delivery_status', sa.Enum('pending', 'released', 'skipped', name='job_delivery_status', native_enum=False, length=32), nullable=False),
    sa.Column('released_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('released_late', sa.Boolean(), nullable=False),
    sa.Column('skipped_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('skipped_by', app.models.GUID(length=36), nullable=True),
    sa.Column('initial_generation_id', app.models.GUID(length=36), nullable=True),
    sa.Column('jd_tsv', sa.Text(), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['maker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['skipped_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maker_id', 'idempotency_key', name='uq_jobs_idempotency'),
    sa.UniqueConstraint('maker_id', 'submitted_date', 'seq_no', name='uq_jobs_ordering_key')
    )
    op.create_index(op.f('ix_jobs_delivery_status'), 'jobs', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_jobs_jd_hash'), 'jobs', ['jd_hash'], unique=False)
    op.create_index(op.f('ix_jobs_maker_id'), 'jobs', ['maker_id'], unique=False)
    op.create_index('ix_jobs_pending_cursor', 'jobs', ['maker_id', 'submitted_date', 'seq_no'], unique=False, postgresql_where=sa.text("delivery_status = 'pending'"), sqlite_where=sa.text("delivery_status = 'pending'"))
    op.create_index(op.f('ix_jobs_submitted_date'), 'jobs', ['submitted_date'], unique=False)
    op.create_table('profile_assignments',
    sa.Column('profile_id', app.models.GUID(length=36), nullable=False),
    sa.Column('maker_id', app.models.GUID(length=36), nullable=False),
    sa.Column('assigned_by', app.models.GUID(length=36), nullable=True),
    sa.Column('started_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('ended_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profile_assignments_active_maker', 'profile_assignments', ['maker_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'), sqlite_where=sa.text('ended_at IS NULL'))
    op.create_index(op.f('ix_profile_assignments_maker_id'), 'profile_assignments', ['maker_id'], unique=False)
    op.create_index(op.f('ix_profile_assignments_profile_id'), 'profile_assignments', ['profile_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', app.models.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('revoked_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_by', app.models.GUID(length=36), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('doc_sets',
    sa.Column('job_id', app.models.GUID(length=36), nullable=False),
    sa.Column('candidate_name', sa.String(length=300), nullable=True),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('job_title', sa.String(length=300), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('storage_dir', sa.String(length=500), nullable=True),
    sa.Column('docx_basename', sa.String(length=300), nullable=True),
    sa.Column('current_generation_id', app.models.GUID(length=36), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('selected_by', app.models.GUID(length=36), nullable=True),
    sa.Column('selected_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('keep', sa.Boolean(), nullable=False),
    sa.Column('renamed_by', app.models.GUID(length=36), nullable=True),
    sa.Column('files_expired_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('search_tsv', sa.Text(), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['renamed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['selected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_doc_sets_company_name'), 'doc_sets', ['company_name'], unique=False)
    op.create_index(op.f('ix_doc_sets_is_selected'), 'doc_sets', ['is_selected'], unique=False)
    op.create_table('generations',
    sa.Column('job_id', app.models.GUID(length=36), nullable=False),
    sa.Column('generation_no', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('initial', 'retry_after_skip', 'regenerate', name='generation_kind', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'llm_running', 'rendering', 'retry_wait', 'needs_attention', 'ready', 'cancelled', name='generation_status', native_enum=False, length=32), nullable=False),
    sa.Column('stage', sa.Enum('llm', 'render', name='generation_stage', native_enum=False, length=32), nullable=False),
    sa.Column('llm_attempts', sa.Integer(), nullable=False),
    sa.Column('render_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_budget_reset_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('next_retry_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('dispatch_state', sa.Enum('pending', 'sent', name='dispatch_state', native_enum=False, length=32), nullable=False),
    sa.Column('dispatched_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('claimed_by', sa.String(length=200), nullable=True),
    sa.Column('lease_token', app.models.GUID(length=36), nullable=True),
    sa.Column('lease_expires_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('consecutive_provider_errors', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_message', sa.String(length=2000), nullable=True),
    sa.Column('prompt_version_id', app.models.GUID(length=36), nullable=True),
    sa.Column('provider_id', app.models.GUID(length=36), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('llm_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('theme_id', app.models.GUID(length=36), nullable=True),
    sa.Column('theme_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('storage_dir', sa.String(length=500), nullable=True),
    sa.Column('ready_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('created_by', app.models.GUID(length=36), nullable=True),
    sa.Column('expired_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'generation_no', name='uq_generation_no')
    )
    op.create_index('ix_generations_dispatch_pending', 'generations', ['dispatch_state', 'status'], unique=False)
    op.create_index(op.f('ix_generations_job_id'), 'generations', ['job_id'], unique=False)
    op.create_index('ix_generations_lease', 'generations', ['lease_expires_at'], unique=False)
    op.create_index('ix_generations_next_retry', 'generations', ['next_retry_at'], unique=False)
    op.create_index('ix_generations_ready_initial', 'generations', ['job_id'], unique=False, postgresql_where=sa.text("status = 'ready' AND kind = 'initial'"), sqlite_where=sa.text("status = 'ready' AND kind = 'initial'"))
    op.create_index(op.f('ix_generations_status'), 'generations', ['status'], unique=False)
    op.create_table('files',
    sa.Column('generation_id', app.models.GUID(length=36), nullable=True),
    sa.Column('doc_set_id', app.models.GUID(length=36), nullable=True),
    sa.Column('kind', sa.Enum('pdf', 'docx', 'txt', 'llm_json', 'meta', 'jd', name='file_kind', native_enum=False, length=32), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('expired_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['doc_set_id'], ['doc_sets.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_doc_set_id'), 'files', ['doc_set_id'], unique=False)
    op.create_index(op.f('ix_files_generation_id'), 'files', ['generation_id'], unique=False)
    op.create_index('ix_files_generation_kind', 'files', ['generation_id', 'kind'], unique=False)
    op.create_table('generation_attempts',
    sa.Column('generation_id', app.models.GUID(length=36), nullable=False),
    sa.Column('stage', sa.Enum('llm', 'render', name='attempt_stage', native_enum=False, length=32), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('lease_token', app.models.GUID(length=36), nullable=True),
    sa.Column('worker', sa.String(length=200), nullable=True),
    sa.Column('provider_id', app.models.GUID(length=36), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('started_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('finished_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('outcome', sa.Enum('succeeded', 'failed', 'timed_out', 'superseded', name='attempt_outcome', native_enum=False, length=32), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_cached', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('artifacts_dir', sa.String(length=500), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_id', 'stage', 'attempt_no', name='uq_attempt_no')
    )
    op.create_index(op.f('ix_generation_attempts_generation_id'), 'generation_attempts', ['generation_id'], unique=False)
    op.create_table('interviews',
    sa.Column('doc_set_id', app.models.GUID(length=36), nullable=False),
    sa.Column('generation_id', app.models.GUID(length=36), nullable=False),
    sa.Column('reviewer_id', app.models.GUID(length=36), nullable=True),
    sa.Column('template_id', app.models.GUID(length=36), nullable=True),
    sa.Column('template_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('meeting_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('meeting_tz', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'no_show', name='interview_status', native_enum=False, length=32), nullable=False),
    sa.Column('created_by', app.models.GUID(length=36), nullable=True),
    sa.Column('cancelled_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('seen_by_reviewer_at', app.models.DateTimeTZ(), nullable=True),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doc_set_id'], ['doc_sets.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['interview_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_doc_set_id'), 'interviews', ['doc_set_id'], unique=False)
    op.create_index(op.f('ix_interviews_meeting_at'), 'interviews', ['meeting_at'], unique=False)
    op.create_index(op.f('ix_interviews_reviewer_id'), 'interviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_table('pipeline_events',
    sa.Column('job_id', app.models.GUID(length=36), nullable=True),
    sa.Column('generation_id', app.models.GUID(length=36), nullable=True),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_events_generation_id'), 'pipeline_events', ['generation_id'], unique=False)
    op.create_index(op.f('ix_pipeline_events_job_id'), 'pipeline_events', ['job_id'], unique=False)
    op.create_table('feedback',
    sa.Column('interview_id', app.models.GUID(length=36), nullable=False),
    sa.Column('author_id', app.models.GUID(length=36), nullable=False),
    sa.Column('outcome', sa.Enum('pass', 'fail', 'hold', 'no_show', name='feedback_outcome', native_enum=False, length=32), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('concerns', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'version_no', name='uq_feedback_version')
    )
    op.create_index(op.f('ix_feedback_interview_id'), 'feedback', ['interview_id'], unique=False)
    op.create_table('interview_events',
    sa.Column('interview_id', app.models.GUID(length=36), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('actor_id', app.models.GUID(length=36), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('id', app.models.GUID(length=36), nullable=False),
    sa.Column('created_at', app.models.DateTimeTZ(), nullable=False),
    sa.Column('updated_at', app.models.DateTimeTZ(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_events_interview_id'), 'interview_events', ['interview_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_events_interview_id'), table_name='interview_events')
    op.drop_table('interview_events')
    op.drop_index(op.f('ix_feedback_interview_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_pipeline_events_job_id'), table_name='pipeline_events')
    op.drop_index(op.f('ix_pipeline_events_generation_id'), table_name='pipeline_events')
    op.drop_table('pipeline_events')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_reviewer_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_meeting_at'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_doc_set_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_generation_attempts_generation_id'), table_name='generation_attempts')
    op.drop_table('generation_attempts')
    op.drop_index('ix_files_generation_kind', table_name='files')
    op.drop_index(op.f('ix_files_generation_id'), table_name='files')
    op.drop_index(op.f('ix_files_doc_set_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_generations_status'), table_name='generations')
    op.drop_index('ix_generations_ready_initial', table_name='generations', postgresql_where=sa.text("status = 'ready' AND kind = 'initial'"), sqlite_where=sa.text("status = 'ready' AND kind = 'initial'"))
    op.drop_index('ix_generations_next_retry', table_name='generations')
    op.drop_index('ix_generations_lease', table_name='generations')
    op.drop_index(op.f('ix_generations_job_id'), table_name='generations')
    op.drop_index('ix_generations_dispatch_pending', table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_doc_sets_is_selected'), table_name='doc_sets')
    op.drop_index(op.f('ix_doc_sets_company_name'), table_name='doc_sets')
    op.drop_table('doc_sets')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_profile_assignments_profile_id'), table_name='profile_assignments')
    op.drop_index(op.f('ix_profile_assignments_maker_id'), table_name='profile_assignments')
    op.drop_index('ix_profile_assignments_active_maker', table_name='profile_assignments', postgresql_where=sa.text('ended_at IS NULL'), sqlite_where=sa.text('ended_at IS NULL'))
    op.drop_table('profile_assignments')
    op.drop_index(op.f('ix_jobs_submitted_date'), table_name='jobs')
    op.drop_index('ix_jobs_pending_cursor', table_name='jobs', postgresql_where=sa.text("delivery_status = 'pending'"), sqlite_where=sa.text("delivery_status = 'pending'"))
    op.drop_index(op.f('ix_jobs_maker_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_jd_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_delivery_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('interview_templates')
    op.drop_index(op.f('ix_daily_maker_stats_maker_id'), table_name='daily_maker_stats')
    op.drop_table('daily_maker_stats')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('worker_heartbeats')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('themes')
    op.drop_index(op.f('ix_system_metrics_key'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_prompt_versions_profile_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_table('profiles')
    op.drop_table('llm_providers')
    op.drop_index('ix_outbox_unpublished', table_name='event_outbox')
    op.drop_table('event_outbox')
    # ### end Alembic commands ###
